### ISSUE TITLE
not sure on this? 

### ISSUE THREAD

**Issue by shez1983** [illuminatech/validation-composite#1]
why cant we create custom RULES a feature laravel already provides - we can then use these anywhere we want just like urs.

**Comment by klimov-paul** [comment]
You can.
`CompositeRule` is just a particular rule of such, which allows quick creation of validation logic re-using the ones already provided by Laravel.
Whether to use this library or not is up to you. If you can't get any benefit from it - don't use it.

**Comment by fgilio** [comment]
Nice package, even I think this functionality should be in Laravel's core

**Comment by klimov-paul** [comment]
I am glad you like it.
If you wish it belonging to the Laravel core, you can suggest it at https://github.com/laravel/ideas
