### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by zarunet** [illuminatech/validation-composite#4]
Is there any plans for this package to support Laravel 6?
https://github.com/illuminatech/validation-composite/blob/86e9e784c61c917c2cc1643e690d83103795263a/composer.json#L18
Currently the composer.json only states compatibility with Laravel 5.8.x.

**Comment by klimov-paul** [comment]
Resolved by commit bc935341eef1f54b302d47d5339692a0da6476d9
