### ISSUE TITLE
Hability to customize validation messages

### ISSUE THREAD

**Issue by gjm** [illuminatech/validation-composite#6]
Should be possible to specify the error message for each of the rules. 

Something like:

```php
<?php

namespace App\Rules;

use Illuminatech\Validation\Composite\CompositeRule;

class PasswordRule extends CompositeRule
{
    protected function rules(): array
    {
        return ['string', 'min:8', 'max:200'];
    }

    protected function messages(): array
    {
        return [
            'string' => 'My custom string message',
            'min' => 'My custom min message',
            'max' => 'My custom max message',
        ];
    }
}
```

Is there some way to achieve this implemented already? Looking at the code I see no way of passing the custom messages to the validator instance that is used to perform the checks.

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.1.0
| Laravel Framework Version | 6.11.0
| PHP version               | 7.4
| Operating system          | Ubuntu 19.10

**Comment by klimov-paul** [comment]
Resolved by commit c85f3c30e14a11c9f3adb73185bb70cc8fa66b0f

**Comment by gjm** [comment]
@klimov-paul Thanks for the fix! Is there an ETA for this to be released?

**Comment by klimov-paul** [comment]
Have you verified "dev-master" works for you?

**Comment by gjm** [comment]
Yes it works. I just preferred to use a *stable* version. Will use `dev-master` for now.

**Comment by klimov-paul** [comment]
https://github.com/illuminatech/validation-composite/releases/tag/1.2.0
